/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hm
 */
public class splash extends javax.swing.JFrame {

    /**
     * Creates new form splash
     */
    public splash() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadingnumber = new javax.swing.JLabel();
        circleloading = new javax.swing.JLabel();
        pw = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();
        developer1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        loadingnumber.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        loadingnumber.setForeground(new java.awt.Color(0, 204, 204));
        loadingnumber.setText("0%");
        jPanel1.add(loadingnumber);
        loadingnumber.setBounds(390, 210, 110, 90);

        circleloading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circle loading.gif"))); // NOI18N
        circleloading.setText("jLabel1");
        jPanel1.add(circleloading);
        circleloading.setBounds(320, 170, 200, 170);

        pw.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 50)); // NOI18N
        pw.setForeground(new java.awt.Color(0, 204, 204));
        pw.setText("Plsease wait");
        jPanel1.add(pw);
        pw.setBounds(210, 30, 430, 130);

        loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loaging_1.gif"))); // NOI18N
        jPanel1.add(loading);
        loading.setBounds(570, 90, 110, 30);

        developer1.setForeground(new java.awt.Color(0, 153, 153));
        developer1.setText("© Developed by sajib");
        jPanel1.add(developer1);
        developer1.setBounds(10, 460, 180, 30);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 4));
        jPanel1.add(background);
        background.setBounds(0, 0, 881, 499);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
              
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
            new splash().setVisible(true);
 
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel circleloading;
    private javax.swing.JLabel developer1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loading;
    public javax.swing.JLabel loadingnumber;
    private javax.swing.JLabel pw;
    // End of variables declaration//GEN-END:variables
}
